name: Publish to Firebase

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Firebase Publish React
        uses: mohammed-atif/firebase-publish-react@v1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
